name: spotify-box
on:
  workflow_dispatch:
  #  schedule:
  #    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  push:
    branches: main
jobs:
  updateTopTracks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lauravuo/spotify-box@main
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      - run: |
          git add tracks.json
          git commit -a -m "Add latest tracks."
          git push
